### ISSUE TITLE
Add support for more date formats

### ISSUE THREAD

**Issue by bitboxer** [dkarter/cookie_monster#4]
I just tried your library, but it does not work with the following cookie:

```
AKA_A2=A; expires=Sat, 14-Oct-2023 16:25:57 GMT; path=/; domain=arket.com; secure; HttpOnly
```

There are three formats for this, sadly:

* Sun, 06 Nov 1994 08:49:37 GMT
* Sunday, 06-Nov-94 08:49:37 GMT 
* Sun Nov 6 08:49:37 1994

See [here](https://www.rfc-editor.org/rfc/rfc6265#section-4.1.1) and [here](https://www.rfc-editor.org/rfc/rfc2616#section-3.3.1) for details.

**Comment by dkarter** [comment]
Hey thanks for the note! I was not aware the deprecated formats are still in wide use. 

It shouldn't be too difficult to add support for all three.

I'll see what I can do.

**Comment by bitboxer** [comment]
Yeah...haven't seen them in the wild, too. But this example is from Akamai, they still use that format 🤯.

**Comment by dkarter** [comment]
Hi @bitboxer - this should be resolved in v1.1.0

https://hex.pm/packages/cookie_monster/1.1.0
https://github.com/dkarter/cookie_monster/releases/tag/v1.1.0

If you care to see the changes the PR is available here #8 

btw.. turns out this 2 digit year format in the deprecated RFC 850 resurfaced some Y2K bug concerns 🙃... I've handled these as best I could and documented everything. It is likely an edge case but I still find it fascinating that we still deal with this stuff to this day. Gonna write a blog post about this in the near future, I think.

**Comment by bitboxer** [comment]
Oh amazing. Thank you for fixing this so quickly ❤️.

**Comment by bitboxer** [comment]
Oh damn, I now realize that akamais format is even weirder. It's actually damaged.

Look at it:


```
AKA_A2=A; expires=Sat, 14-Oct-2023 16:25:57 GMT; path=/; domain=arket.com; secure; HttpOnly
```

It uses **Sat,**, the short form for the weekdays 🙈. It is clearly wrong, but Firefox, Chrome and Safari are okay with the short form weekday in that format 🤷.

Oh man...super sorry. Your library now returns an "invalid date", which is correct, but the real world uses this damaged format.

**Comment by dkarter** [comment]
Try v1.1.1 it should be pushed to hex by CI momentarily

**Comment by bitboxer** [comment]
Yes, that one works 🎉. Wow, you are quick. Thank you.
